name: BonFHIR CI

on:
  push:
    branches: [main]
permissions: 
  contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm build

      - name: Check & Test
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm check && pnpm test

      - name: Configure publishing
        run: |
          echo @bonfhir:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/storybook/dist
          repository-name: bonfhir/storybook-pages
          branch: main
          clean: true
          token: ${{ secrets.STORYBOOK_PUBLISH_TOKEN }}
          git-config-name: gh-actions
          git-config-email: actions@github.com

